# Make mesh data for importing into FreeCAD

Using the Open3D Python package

In [1]:
import os
import numpy as np
import open3d as o3d

[Warning] Since Open3D 0.15, installing Open3D via conda is deprecated. Please re-install Open3D via: `pip install open3d -U`.


In [2]:
data_dir = "data"

## Examples from Open3D docs

In [3]:
armadillo_mesh = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo_mesh.path)

knot_mesh = o3d.data.KnotMesh()
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

TriangleMesh with 1440 points and 2880 triangles.
Vertices:
[[  4.51268387  28.68865967 -76.55680847]
 [  7.63622284  35.52046967 -69.78063965]
 [  6.21986008  44.22465134 -64.82303619]
 ...
 [-22.12651634  31.28466606 -87.37570953]
 [-13.91188431  25.4865818  -86.25827026]
 [ -5.27768707  23.36245346 -81.43279266]]
Triangles:
[[   0   12   13]
 [   0   13    1]
 [   1   13   14]
 ...
 [1438   11 1439]
 [1439   11    0]
 [1439    0 1428]]


In [4]:
o3d.visualization.draw_geometries([mesh])

In [5]:
np.asarray(mesh.vertices).shape

(1440, 3)

In [6]:
np.asarray(mesh.triangles)

array([[   0,   12,   13],
       [   0,   13,    1],
       [   1,   13,   14],
       ...,
       [1438,   11, 1439],
       [1439,   11,    0],
       [1439,    0, 1428]], dtype=int32)

In [15]:
vertices = np.asarray(mesh.vertices)
vertices.shape

(1440, 3)

In [23]:
triangles = np.asarray(mesh.triangles)
triangles.shape

(2880, 3)

In [26]:
# Combine vertices and triangles arrays into one large
# array of triangle vertices
triangle = triangles[0]
vertices[triangle]

array([[  4.51268387,  28.68865967, -76.55680847],
       [  7.50471115,  31.48498535, -79.55582428],
       [ 10.86927032,  39.31740952, -74.10792542]])

In [29]:
vertices[triangles[1]]

array([[  4.51268387,  28.68865967, -76.55680847],
       [ 10.86927032,  39.31740952, -74.10792542],
       [  7.63622284,  35.52046967, -69.78063965]])

In [30]:
vertices[triangles[2]]

array([[  7.63622284,  35.52046967, -69.78063965],
       [ 10.86927032,  39.31740952, -74.10792542],
       [  9.63236618,  48.72576141, -70.60083771]])

In [31]:
vertices[triangles[0:3]].shape

(3, 3, 3)

In [32]:
vertices[triangles[0:3]].reshape(9, 3)

array([[  4.51268387,  28.68865967, -76.55680847],
       [  7.50471115,  31.48498535, -79.55582428],
       [ 10.86927032,  39.31740952, -74.10792542],
       [  4.51268387,  28.68865967, -76.55680847],
       [ 10.86927032,  39.31740952, -74.10792542],
       [  7.63622284,  35.52046967, -69.78063965],
       [  7.63622284,  35.52046967, -69.78063965],
       [ 10.86927032,  39.31740952, -74.10792542],
       [  9.63236618,  48.72576141, -70.60083771]])

In [34]:
triangle_data = vertices[triangles].reshape(-1, 3)
triangle_data.shape

(8640, 3)

In [35]:
filename = "armadillo_mesh.csv"
np.savetxt(os.path.join(data_dir, filename), triangle_data)

In [36]:
triangle_data = np.loadtxt(os.path.join(data_dir, filename))
triangle_data.shape

(8640, 3)

In [37]:
assert(triangle_data.shape == (8640, 3))